version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: docker build --rm=false -t widla/golang-builder .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push widla/golang-builder